version: '1'

services:
  postgres-akbank:
    image: postgres:latest
    container_name: postgres-db-akbank
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: akbank
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    networks:
      - mynetwork

  akbank-service:
    build: ./akbank-service
    container_name: akbank-service
    image: akbank-image:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres-akbank
      - kredinbizde-discovery
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/akbank
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://kredinbizde-discovery:8761/eureka
    networks:
      - mynetwork

  postgres-garanti:
    image: postgres:latest
    container_name: postgres-db-garanti
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: garanti
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    networks:
      - mynetwork

  garanti-service:
    build: ./garanti-service
    container_name: garanti-service
    image: garanti-image:latest
    ports:
      - "8083:8083"
    depends_on:
      - postgres-garanti
      - kredinbizde-discovery
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/garanti
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://kredinbizde-discovery:8761/eureka
    networks:
      - mynetwork

  kredinbizde-discovery:
    build: ./kredinbizde-discovery
    container_name: kredinbizde-discovery
    image: kredinbizde-discovery-image:latest
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  kredinbizde-gw:
    build: ./kredinbizde-gw
    container_name: kredinbizde-gw
    image: kredinbizde-gw-image:latest
    ports:
      - "8084:8084"
    depends_on:
      - kredinbizde-discovery
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://kredinbizde-discovery:8761/eureka
    networks:
      - mynetwork

  postgres-kredinbizde:
    image: postgres:latest
    container_name: postgres-db-kredinbizde
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kredinbizde
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - mynetwork

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafkaa
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - mynetwork

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeperr
    restart: always
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  kredinbizde-service:
    build: ./kredinbizde-service
    container_name: kredinbizde-service
    image: kredinbizde-service-image:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres-kredinbizde
      - rabbitmq
      - kafka
      - redis
      - kredinbizde-discovery
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kredinbizde
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 123456
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://kredinbizde-discovery:8761/eureka
    networks:
      - mynetwork

  notification-service:
    build: ./notification-service
    container_name: notification-service
    image: notification-service-image:latest
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - kredinbizde-discovery
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://kredinbizde-discovery:8761/eureka
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge