version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db-akbank
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: akbank
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password

  app:
    build: ./
    container_name: akbank-service
    image: akbank-image:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/akbank
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_password