server:
  port: 8084
spring:
  application:
    name: kredinbizde-gateway
  cloud:
    gateway:
      routes:
        - id: kredinbizde-service
          uri: lb://KREDINBIZDE-SERVICE
          predicates:
             - Path=/api/**